### ISSUE TITLE
Put FAQ and Tutorials in bucket root

### ISSUE THREAD

**Issue by lucasdittrichzup** [ZupIT/ritchie-docs#126]
As the FAQ and Tutorials are the same for the different versions, it is suggested to place them at the root of the bucket. This will make the space used in S3 better utilized.

Thus, upload workflows must be handled to, in addition to images, upload the FAQ and Tutorials in the root of the bucket.

**Comment by jessica-tw** [comment]
PR made by @darwinaraujozup https://github.com/ZupIT/ritchie-docs/pull/135

**Comment by jessica-tw** [comment]
PR merged.
