### ISSUE TITLE
Update the Docs footer License to Creative Commons

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/ritchie-docs#129]
Please, could you update the license footer to use Creative Commons instead?

https://creativecommons.org/licenses/by/4.0/

You can use this site as a reference:

https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en

Simple sample of footer

```html
<p>&copy; 2021 Zup IT <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons</a> <a href="https://insights.zup.com.br/politica-privacidade">Privacy Policy</a></p>
```

Ps: In the English version, we need to check the English version of this policy: https://insights.zup.com.br/politica-privacidade

Docs website: https://docs.ritchiecli.io/v2.11/

**Comment by GuillaumeFalourd** [comment]
Thank you for opening this ISSUE @otaviojava 👍🏼 
Do you know if there is an english version of the Zup IT privacy politics? 
_For what I know it is not available yet, but I might simply not know where it is located._

**Comment by otaviojava** [comment]
@GuillaumeFalourd I don't know.
I'm checking; for now, we can use the Portuguese reference for a while.

**Comment by darwinaraujozup** [comment]
Done!

https://github.com/ZupIT/ritchie-webpage/pull/65
